server:
  port: 7070
  context-path: /services
  
security:
  oauth2:
    client:
      access-token-uri: http://localhost:9999/spring-security-oauth-server/oauth/token
      user-authorization-uri: http://localhost:9999/spring-security-oauth-server/oauth/authorize
      client-id: commandlineinterface
      client-secret: commandlineinterface
    resource:
      user-info-uri: http://localhost:9999/spring-security-oauth-server/user
  
spring:
  application:
    name: employee-service
  jpa:
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: http://localhost:8080
  sleuth:
    sampler:
      percentage: 1.0
    
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.cloud.sleuth: DEBUG
    org.springframework.security: DEBUG
    