server:
  port: 7070
  
security:
  oauth2:
    client:
      access-token-uri: http://localhost:9999/oauth/token
      user-authorization-uri: http://localhost:9999/oauth/authorize
      client-id: commandlineinterface
      client-secret: commandlineinterface
    resource:
      user-info-uri: http://localhost:9999/user
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/EMPLOYEE_DB
    username: rdurgesh
    password: rdurgesh
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: validate
  zipkin:
    base-url: http://localhost:7777
  sleuth:
    sampler:
      percentage: 1.0
    
logging:
  level:
    root: INFO 
    org.springframework.web: INFO
    org.springframework.cloud.sleuth: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /logs/employee-service/employee-service.log
    